from typing import Dict, List

# --- Canonical Catalog of Action-Based Permissions ---
CANONICAL_PERMISSIONS_CATALOG: List[Dict[str, str | None]] = [
    # 1. Organization Management (F004)
    {
        "code": "organization.read",
        "name": "Consultar Organizaciones",
        "description": "Visualizar información y árbol de organizaciones",
        "category": "ORGANIZATION",
        "resource": "organization",
        "action": "read",
        "risk_level": "LOW",
        "future_phase_owner": None,
    },
    {
        "code": "organization.create",
        "name": "Crear Organización",
        "description": "Registrar nuevas organizaciones en el sistema",
        "category": "ORGANIZATION",
        "resource": "organization",
        "action": "create",
        "risk_level": "MEDIUM",
        "future_phase_owner": None,
    },
    {
        "code": "organization.update",
        "name": "Modificar Organización",
        "description": "Actualizar datos y configuración de organizaciones",
        "category": "ORGANIZATION",
        "resource": "organization",
        "action": "update",
        "risk_level": "MEDIUM",
        "future_phase_owner": None,
    },
    {
        "code": "organization.delete",
        "name": "Eliminar Organización",
        "description": "Eliminar organizaciones sin sedes activas",
        "category": "ORGANIZATION",
        "resource": "organization",
        "action": "delete",
        "risk_level": "HIGH",
        "future_phase_owner": None,
    },
    # 2. Branch Management (F004)
    {
        "code": "branch.read",
        "name": "Consultar Sedes",
        "description": "Visualizar sedes y sus ubicaciones operativas",
        "category": "ORGANIZATION",
        "resource": "branch",
        "action": "read",
        "risk_level": "LOW",
        "future_phase_owner": None,
    },
    {
        "code": "branch.create",
        "name": "Crear Sede",
        "description": "Registrar nuevas sedes y geolocalización",
        "category": "ORGANIZATION",
        "resource": "branch",
        "action": "create",
        "risk_level": "MEDIUM",
        "future_phase_owner": None,
    },
    {
        "code": "branch.update",
        "name": "Modificar Sede",
        "description": "Actualizar información y coordenadas de sedes",
        "category": "ORGANIZATION",
        "resource": "branch",
        "action": "update",
        "risk_level": "MEDIUM",
        "future_phase_owner": None,
    },
    {
        "code": "branch.delete",
        "name": "Eliminar Sede",
        "description": "Eliminar sedes sin almacenes asociados",
        "category": "ORGANIZATION",
        "resource": "branch",
        "action": "delete",
        "risk_level": "HIGH",
        "future_phase_owner": None,
    },
    # 3. Warehouse Management (F004)
    {
        "code": "warehouse.read",
        "name": "Consultar Almacenes",
        "description": "Visualizar almacenes y características operativas",
        "category": "WAREHOUSE",
        "resource": "warehouse",
        "action": "read",
        "risk_level": "LOW",
        "future_phase_owner": None,
    },
    {
        "code": "warehouse.create",
        "name": "Crear Almacén",
        "description": "Registrar nuevos almacenes en una sede",
        "category": "WAREHOUSE",
        "resource": "warehouse",
        "action": "create",
        "risk_level": "MEDIUM",
        "future_phase_owner": None,
    },
    {
        "code": "warehouse.update",
        "name": "Modificar Almacén",
        "description": "Actualizar datos y ubicación de almacenes",
        "category": "WAREHOUSE",
        "resource": "warehouse",
        "action": "update",
        "risk_level": "MEDIUM",
        "future_phase_owner": None,
    },
    {
        "code": "warehouse.delete",
        "name": "Eliminar Almacén",
        "description": "Eliminar almacenes del catálogo",
        "category": "WAREHOUSE",
        "resource": "warehouse",
        "action": "delete",
        "risk_level": "HIGH",
        "future_phase_owner": None,
    },
    # 4. Roles Management (F005)
    {
        "code": "roles.read",
        "name": "Consultar Roles",
        "description": "Ver catálogo de roles y matrices RBAC",
        "category": "SECURITY",
        "resource": "roles",
        "action": "read",
        "risk_level": "LOW",
        "future_phase_owner": None,
    },
    {
        "code": "roles.create",
        "name": "Crear Rol",
        "description": "Crear roles personalizados por organización",
        "category": "SECURITY",
        "resource": "roles",
        "action": "create",
        "risk_level": "MEDIUM",
        "future_phase_owner": None,
    },
    {
        "code": "roles.update",
        "name": "Modificar Rol",
        "description": "Actualizar nombre y descripción de roles",
        "category": "SECURITY",
        "resource": "roles",
        "action": "update",
        "risk_level": "MEDIUM",
        "future_phase_owner": None,
    },
    {
        "code": "roles.delete",
        "name": "Eliminar Rol",
        "description": "Eliminar roles personalizados",
        "category": "SECURITY",
        "resource": "roles",
        "action": "delete",
        "risk_level": "HIGH",
        "future_phase_owner": None,
    },
    # 5. Permissions Management (F006)
    {
        "code": "permissions.read",
        "name": "Consultar Permisos",
        "description": "Ver catálogo de permisos y asignaciones",
        "category": "SECURITY",
        "resource": "permissions",
        "action": "read",
        "risk_level": "LOW",
        "future_phase_owner": None,
    },
    {
        "code": "permissions.assign",
        "name": "Asignar Permisos a Roles",
        "description": "Modificar la matriz de permisos de roles",
        "category": "SECURITY",
        "resource": "permissions",
        "action": "assign",
        "risk_level": "CRITICAL",
        "future_phase_owner": None,
    },
    # 5.1 User Administration (F008)
    {
        "code": "users.read",
        "name": "Consultar Usuarios",
        "description": "Visualizar listado y detalle de usuarios",
        "category": "SECURITY",
        "resource": "users",
        "action": "read",
        "risk_level": "LOW",
        "future_phase_owner": None,
    },
    {
        "code": "users.create",
        "name": "Crear Usuario",
        "description": "Aprovisionar nuevos usuarios en la organización",
        "category": "SECURITY",
        "resource": "users",
        "action": "create",
        "risk_level": "HIGH",
        "future_phase_owner": None,
    },
    {
        "code": "users.update",
        "name": "Modificar Usuario",
        "description": "Actualizar datos y contraseña de usuarios",
        "category": "SECURITY",
        "resource": "users",
        "action": "update",
        "risk_level": "HIGH",
        "future_phase_owner": None,
    },
    {
        "code": "users.disable",
        "name": "Desactivar Usuario",
        "description": "Inactivar usuarios y revocar sus sesiones",
        "category": "SECURITY",
        "resource": "users",
        "action": "disable",
        "risk_level": "HIGH",
        "future_phase_owner": None,
    },
    {
        "code": "users.roles.assign",
        "name": "Asignar Roles a Usuario",
        "description": "Vincular perfiles y permisos a usuarios",
        "category": "SECURITY",
        "resource": "users",
        "action": "assign",
        "risk_level": "CRITICAL",
        "future_phase_owner": None,
    },
    # 6. Purchasing Domain (F031)
    {
        "code": "purchasing.read",
        "name": "Consultar Compras",
        "description": "Visualizar requerimientos y órdenes de compra",
        "category": "PURCHASING",
        "resource": "purchasing",
        "action": "read",
        "risk_level": "LOW",
        "future_phase_owner": "F031",
    },
    {
        "code": "purchasing.create",
        "name": "Crear Orden de Compra",
        "description": "Generar requerimientos y órdenes de compra",
        "category": "PURCHASING",
        "resource": "purchasing",
        "action": "create",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F031",
    },
    {
        "code": "purchasing.update",
        "name": "Modificar Orden de Compra",
        "description": "Editar términos de órdenes de compra",
        "category": "PURCHASING",
        "resource": "purchasing",
        "action": "update",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F031",
    },
    {
        "code": "purchasing.approve",
        "name": "Aprobar Orden de Compra",
        "description": "Autorizar financieramente órdenes de compra",
        "category": "PURCHASING",
        "resource": "purchasing",
        "action": "approve",
        "risk_level": "HIGH",
        "future_phase_owner": "F031",
    },
    # 7. Receiving Domain (F037)
    {
        "code": "receiving.read",
        "name": "Consultar Recepciones",
        "description": "Visualizar ingresos en muelle y recepciones",
        "category": "RECEIVING",
        "resource": "receiving",
        "action": "read",
        "risk_level": "LOW",
        "future_phase_owner": "F037",
    },
    {
        "code": "receiving.create",
        "name": "Registrar Recepción",
        "description": "Ingresar descarga física y cotejo de bultos",
        "category": "RECEIVING",
        "resource": "receiving",
        "action": "create",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F037",
    },
    {
        "code": "receiving.verify",
        "name": "Verificar Discrepancias",
        "description": "Validar diferencias contra guía de remisión",
        "category": "RECEIVING",
        "resource": "receiving",
        "action": "verify",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F037",
    },
    # 8. Quality Control (F042)
    {
        "code": "quality.read",
        "name": "Consultar Evaluaciones de Calidad",
        "description": "Ver dictámenes técnicos y estados de cuarentena",
        "category": "QUALITY",
        "resource": "quality",
        "action": "read",
        "risk_level": "LOW",
        "future_phase_owner": "F042",
    },
    {
        "code": "quality.inspect",
        "name": "Registrar Inspección de Calidad",
        "description": "Muestreo y registro de conformidad técnica",
        "category": "QUALITY",
        "resource": "quality",
        "action": "inspect",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F042",
    },
    {
        "code": "quality.quarantine.release",
        "name": "Liberar Cuarentena",
        "description": "Liberar lotes en cuarentena para disponibilidad",
        "category": "QUALITY",
        "resource": "quality",
        "action": "release",
        "risk_level": "HIGH",
        "future_phase_owner": "F042",
    },
    # 9. Physical Warehouse Operations (F044)
    {
        "code": "warehouse.putaway",
        "name": "Ejecutar Putaway",
        "description": "Ubicar mercadería recibida en racks/bahías",
        "category": "WAREHOUSE",
        "resource": "warehouse",
        "action": "putaway",
        "risk_level": "LOW",
        "future_phase_owner": "F044",
    },
    {
        "code": "warehouse.pick",
        "name": "Ejecutar Picking",
        "description": "Preparación física de pedidos en estantes",
        "category": "WAREHOUSE",
        "resource": "warehouse",
        "action": "pick",
        "risk_level": "LOW",
        "future_phase_owner": "F044",
    },
    {
        "code": "warehouse.relocate",
        "name": "Reubicar Mercadería",
        "description": "Traslados entre ubicaciones del mismo almacén",
        "category": "WAREHOUSE",
        "resource": "warehouse",
        "action": "relocate",
        "risk_level": "LOW",
        "future_phase_owner": "F044",
    },
    # 10. Inventory & Kardex (F047)
    {
        "code": "inventory.read",
        "name": "Consultar Inventario y Kardex",
        "description": "Visualizar saldos de stock, lotes y movimientos",
        "category": "INVENTORY",
        "resource": "inventory",
        "action": "read",
        "risk_level": "LOW",
        "future_phase_owner": "F047",
    },
    {
        "code": "inventory.count",
        "name": "Registrar Conteo Cíclico",
        "description": "Ingresar conteos físicos de inventario",
        "category": "INVENTORY",
        "resource": "inventory",
        "action": "count",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F047",
    },
    {
        "code": "inventory.transfer",
        "name": "Transferir entre Almacenes",
        "description": "Iniciar o confirmar traslados de stock",
        "category": "INVENTORY",
        "resource": "inventory",
        "action": "transfer",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F047",
    },
    {
        "code": "inventory.adjust",
        "name": "Ajustar Stock",
        "description": "Ajuste manual de saldos por faltantes o mermas",
        "category": "INVENTORY",
        "resource": "inventory",
        "action": "adjust",
        "risk_level": "HIGH",
        "future_phase_owner": "F047",
    },
    # 11. Dispatch & Packing (F054)
    {
        "code": "dispatch.read",
        "name": "Consultar Despachos",
        "description": "Visualizar pedidos preparados y hojas de carga",
        "category": "DISPATCH",
        "resource": "dispatch",
        "action": "read",
        "risk_level": "LOW",
        "future_phase_owner": "F054",
    },
    {
        "code": "dispatch.pack",
        "name": "Ejecutar Packing y Embalaje",
        "description": "Empaque, rotulado y pesaje de bultos",
        "category": "DISPATCH",
        "resource": "dispatch",
        "action": "pack",
        "risk_level": "LOW",
        "future_phase_owner": "F054",
    },
    {
        "code": "dispatch.load",
        "name": "Cargar Vehículo",
        "description": "Verificar y cargar bultos a unidad de transporte",
        "category": "DISPATCH",
        "resource": "dispatch",
        "action": "load",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F054",
    },
    {
        "code": "dispatch.emit",
        "name": "Emitir Acta de Despacho",
        "description": "Liberar y despachar carga formalmente de muelle",
        "category": "DISPATCH",
        "resource": "dispatch",
        "action": "emit",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F054",
    },
    # 12. Transport Planning (F061)
    {
        "code": "transport.plan",
        "name": "Planificar Rutas de Transporte",
        "description": "Planificar viajes, cronogramas y cubicaje",
        "category": "TRANSPORT",
        "resource": "transport",
        "action": "plan",
        "risk_level": "LOW",
        "future_phase_owner": "F061",
    },
    {
        "code": "transport.route.manage",
        "name": "Administrar Rutas y Tiempos",
        "description": "Configurar rutas maestras y tiempos estándar",
        "category": "TRANSPORT",
        "resource": "transport",
        "action": "manage",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F061",
    },
    {
        "code": "transport.vehicle.assign",
        "name": "Asignar Vehículo y Conductor",
        "description": "Vincular chofer y unidad vehicular a un viaje",
        "category": "TRANSPORT",
        "resource": "transport",
        "action": "assign",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F061",
    },
    # 13. Driver Operations (F071)
    {
        "code": "driver.trip.read",
        "name": "Consultar Viajes Asignados",
        "description": "Ver manifiesto de viaje y paradas del conductor",
        "category": "DRIVER",
        "resource": "driver",
        "action": "read",
        "risk_level": "LOW",
        "future_phase_owner": "F071",
    },
    {
        "code": "driver.trip.update",
        "name": "Actualizar Estado de Viaje",
        "description": "Reportar inicio de ruta, paradas e incidencias",
        "category": "DRIVER",
        "resource": "driver",
        "action": "update",
        "risk_level": "LOW",
        "future_phase_owner": "F071",
    },
    {
        "code": "driver.delivery.confirm",
        "name": "Confirmar Entrega en Destino",
        "description": "Registrar firma digital y evidencia de entrega",
        "category": "DRIVER",
        "resource": "driver",
        "action": "confirm",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F071",
    },
    {
        "code": "driver.trip.close",
        "name": "Cerrar Viaje",
        "description": "Cierre operativo y liquidación de ruta",
        "category": "DRIVER",
        "resource": "driver",
        "action": "close",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F071",
    },
    # 14. Document Catalog & Generation (F011, F026)
    {
        "code": "document_catalog.read",
        "name": "Consultar Catálogo Documental",
        "description": "Visualizar familias, tipos documentales, estados, campos y versiones",
        "category": "DOCUMENTS",
        "resource": "document_catalog",
        "action": "read",
        "risk_level": "LOW",
        "future_phase_owner": None,
    },
    {
        "code": "document_catalog.manage",
        "name": "Administrar Catálogo Documental",
        "description": "Crear y actualizar tipos documentales y publicar nuevas versiones",
        "category": "DOCUMENTS",
        "resource": "document_catalog",
        "action": "manage",
        "risk_level": "HIGH",
        "future_phase_owner": None,
    },
    {
        "code": "document_series.read",
        "name": "Consultar Series Documentales",
        "description": "Visualizar series digitales, rangos reservados y correlativos",
        "category": "DOCUMENTS",
        "resource": "document_series",
        "action": "read",
        "risk_level": "LOW",
        "future_phase_owner": None,
    },
    {
        "code": "document_series.create",
        "name": "Crear Series Documentales",
        "description": "Aperturar nuevas series digitales por tipo, sede y periodo",
        "category": "DOCUMENTS",
        "resource": "document_series",
        "action": "create",
        "risk_level": "HIGH",
        "future_phase_owner": None,
    },
    {
        "code": "document_series.reserve",
        "name": "Reservar Correlativos",
        "description": "Reservar rangos de correlativos y talonarios para emisión",
        "category": "DOCUMENTS",
        "resource": "document_series",
        "action": "reserve",
        "risk_level": "HIGH",
        "future_phase_owner": None,
    },
    {
        "code": "document_series.void",
        "name": "Anular Correlativos",
        "description": "Anular números correlativos reservados sin reutilización",
        "category": "DOCUMENTS",
        "resource": "document_series",
        "action": "void",
        "risk_level": "HIGH",
        "future_phase_owner": None,
    },
    {
        "code": "document_series.download",
        "name": "Descargar Talonarios",
        "description": "Exportar talonarios técnicos de numeración en formato CSV",
        "category": "DOCUMENTS",
        "resource": "document_series",
        "action": "download",
        "risk_level": "LOW",
        "future_phase_owner": None,
    },
    {
        "code": "documents.emit",
        "name": "Emitir Documentos",
        "description": "Generar guías de remisión y actas oficiales",
        "category": "DOCUMENTS",
        "resource": "documents",
        "action": "emit",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F026",
    },
    {
        "code": "documents.download",
        "name": "Descargar Documentos",
        "description": "Descargar PDFs y hojas de ruta generadas",
        "category": "DOCUMENTS",
        "resource": "documents",
        "action": "download",
        "risk_level": "LOW",
        "future_phase_owner": "F026",
    },
    {
        "code": "documents.reprint",
        "name": "Reimprimir Documentos",
        "description": "Reimpresión controlada de guías con auditoría",
        "category": "DOCUMENTS",
        "resource": "documents",
        "action": "reprint",
        "risk_level": "LOW",
        "future_phase_owner": "F026",
    },
    {
        "code": "documents.void",
        "name": "Anular Documentos",
        "description": "Anular guías de remisión o actas emitidas",
        "category": "DOCUMENTS",
        "resource": "documents",
        "action": "void",
        "risk_level": "HIGH",
        "future_phase_owner": "F026",
    },
    # 15. Reports & Analytics (F081)
    {
        "code": "reports.view",
        "name": "Visualizar Reportes y Dashboards",
        "description": "Ver paneles analíticos y métricas operativas",
        "category": "REPORTS",
        "resource": "reports",
        "action": "view",
        "risk_level": "LOW",
        "future_phase_owner": "F081",
    },
    {
        "code": "reports.export",
        "name": "Exportar Reportes a Excel/CSV",
        "description": "Descargar reportes masivos de datos",
        "category": "REPORTS",
        "resource": "reports",
        "action": "export",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F081",
    },
    # 16. Audit & Traceability (F007)
    {
        "code": "audit.read",
        "name": "Consultar Bitácoras de Auditoría",
        "description": "Ver registro append-only de auditoría y trazabilidad",
        "category": "AUDIT",
        "resource": "audit",
        "action": "read",
        "risk_level": "LOW",
        "future_phase_owner": "F007",
    },
    {
        "code": "audit.export",
        "name": "Exportar Evidencias de Auditoría",
        "description": "Exportar informes de control interno y trazabilidad",
        "category": "AUDIT",
        "resource": "audit",
        "action": "export",
        "risk_level": "MEDIUM",
        "future_phase_owner": "F007",
    },
]

# --- Baseline Role Permission Mappings (Principle of Least Privilege) ---
CANONICAL_ROLE_BASELINES: Dict[str, List[str]] = {
    "PURCHASING": [
        "organization.read",
        "branch.read",
        "warehouse.read",
        "purchasing.read",
        "purchasing.create",
        "purchasing.update",
        "purchasing.approve",
        "reports.view",
    ],
    "RECEIVING": [
        "organization.read",
        "branch.read",
        "warehouse.read",
        "receiving.read",
        "receiving.create",
        "receiving.verify",
        "reports.view",
    ],
    "QUALITY": [
        "organization.read",
        "branch.read",
        "warehouse.read",
        "receiving.read",
        "quality.read",
        "quality.inspect",
        "quality.quarantine.release",
        "reports.view",
    ],
    "WAREHOUSE": [
        "organization.read",
        "branch.read",
        "warehouse.read",
        "warehouse.putaway",
        "warehouse.pick",
        "warehouse.relocate",
        "inventory.read",
        "document_series.read",
        "document_series.reserve",
        "document_series.download",
    ],
    "INVENTORY": [
        "organization.read",
        "branch.read",
        "warehouse.read",
        "inventory.read",
        "inventory.count",
        "inventory.transfer",
        "inventory.adjust",
        "reports.view",
    ],
    "DISPATCH": [
        "organization.read",
        "branch.read",
        "warehouse.read",
        "dispatch.read",
        "dispatch.pack",
        "dispatch.load",
        "dispatch.emit",
        "documents.emit",
        "documents.download",
        "documents.reprint",
    ],
    "TRANSPORT": [
        "organization.read",
        "branch.read",
        "warehouse.read",
        "transport.plan",
        "transport.route.manage",
        "transport.vehicle.assign",
        "reports.view",
    ],
    "DRIVER": [
        "driver.trip.read",
        "driver.trip.update",
        "driver.delivery.confirm",
        "driver.trip.close",
        "documents.download",
    ],
    "AUDITOR": [
        "organization.read",
        "branch.read",
        "warehouse.read",
        "roles.read",
        "permissions.read",
        "purchasing.read",
        "receiving.read",
        "quality.read",
        "inventory.read",
        "dispatch.read",
        "driver.trip.read",
        "document_catalog.read",
        "documents.download",
        "reports.view",
        "reports.export",
        "audit.read",
        "audit.export",
        "document_series.read",
        "document_series.download",
    ],
    "MANAGEMENT": [
        "organization.read",
        "organization.create",
        "organization.update",
        "organization.delete",
        "branch.read",
        "branch.create",
        "branch.update",
        "branch.delete",
        "warehouse.read",
        "warehouse.create",
        "warehouse.update",
        "warehouse.delete",
        "roles.read",
        "roles.create",
        "roles.update",
        "roles.delete",
        "permissions.read",
        "permissions.assign",
        "users.read",
        "users.create",
        "users.update",
        "users.disable",
        "users.roles.assign",
        "purchasing.read",
        "purchasing.create",
        "purchasing.update",
        "purchasing.approve",
        "receiving.read",
        "quality.read",
        "inventory.read",
        "dispatch.read",
        "transport.plan",
        "driver.trip.read",
        "document_catalog.read",
        "document_catalog.manage",
        "documents.download",
        "reports.view",
        "reports.export",
        "audit.read",
        "audit.export",
        "document_series.read",
        "document_series.create",
        "document_series.reserve",
        "document_series.void",
        "document_series.download",
    ],
}

# --- Canonical Endpoint ↔ Permission Security Matrix ---
ENDPOINT_PERMISSION_MATRIX = [
    {
        "endpoint": "/api/logistics/structure",
        "method": "GET",
        "permission": "organization.read",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/organizations",
        "method": "POST",
        "permission": "organization.create",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/organizations",
        "method": "GET",
        "permission": "organization.read",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/organizations/{id}",
        "method": "GET",
        "permission": "organization.read",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/organizations/{id}",
        "method": "PATCH",
        "permission": "organization.update",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/organizations/{id}",
        "method": "DELETE",
        "permission": "organization.delete",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/organizations/{id}/branches",
        "method": "POST",
        "permission": "branch.create",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/organizations/{id}/branches",
        "method": "GET",
        "permission": "branch.read",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/branches/{id}",
        "method": "GET",
        "permission": "branch.read",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/branches/{id}",
        "method": "PATCH",
        "permission": "branch.update",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/branches/{id}",
        "method": "DELETE",
        "permission": "branch.delete",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/branches/{id}/warehouses",
        "method": "POST",
        "permission": "warehouse.create",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/branches/{id}/warehouses",
        "method": "GET",
        "permission": "warehouse.read",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/warehouses/{id}",
        "method": "GET",
        "permission": "warehouse.read",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/warehouses/{id}",
        "method": "PATCH",
        "permission": "warehouse.update",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/warehouses/{id}",
        "method": "DELETE",
        "permission": "warehouse.delete",
        "phase": "F004",
    },
    {
        "endpoint": "/api/logistics/roles",
        "method": "GET",
        "permission": "roles.read",
        "phase": "F005",
    },
    {
        "endpoint": "/api/logistics/roles",
        "method": "POST",
        "permission": "roles.create",
        "phase": "F005",
    },
    {
        "endpoint": "/api/logistics/roles/{id}",
        "method": "GET",
        "permission": "roles.read",
        "phase": "F005",
    },
    {
        "endpoint": "/api/logistics/roles/{id}",
        "method": "PATCH",
        "permission": "roles.update",
        "phase": "F005",
    },
    {
        "endpoint": "/api/logistics/roles/{id}",
        "method": "DELETE",
        "permission": "roles.delete",
        "phase": "F005",
    },
    {
        "endpoint": "/api/logistics/roles/matrix",
        "method": "GET",
        "permission": "roles.read",
        "phase": "F005.1",
    },
    {
        "endpoint": "/api/logistics/permissions",
        "method": "GET",
        "permission": "permissions.read",
        "phase": "F006",
    },
    {
        "endpoint": "/api/logistics/permissions/endpoint-matrix",
        "method": "GET",
        "permission": "permissions.read",
        "phase": "F006",
    },
    {
        "endpoint": "/api/logistics/permissions/{id}",
        "method": "GET",
        "permission": "permissions.read",
        "phase": "F006",
    },
    {
        "endpoint": "/api/logistics/roles/{id}/permissions",
        "method": "GET",
        "permission": "permissions.read",
        "phase": "F006",
    },
    {
        "endpoint": "/api/logistics/roles/{id}/permissions",
        "method": "PUT",
        "permission": "permissions.assign",
        "phase": "F006",
    },
    {
        "endpoint": "/api/logistics/audit-events",
        "method": "GET",
        "permission": "audit.read",
        "phase": "F007",
    },
    {
        "endpoint": "/api/logistics/audit-events/export",
        "method": "GET",
        "permission": "audit.export",
        "phase": "F007",
    },
    {
        "endpoint": "/api/logistics/audit-events/{id}",
        "method": "GET",
        "permission": "audit.read",
        "phase": "F007",
    },
    {
        "endpoint": "/api/logistics/users",
        "method": "GET",
        "permission": "users.read",
        "phase": "F008",
    },
    {
        "endpoint": "/api/logistics/users",
        "method": "POST",
        "permission": "users.create",
        "phase": "F008",
    },
    {
        "endpoint": "/api/logistics/users/{id}",
        "method": "GET",
        "permission": "users.read",
        "phase": "F008",
    },
    {
        "endpoint": "/api/logistics/users/{id}",
        "method": "PATCH",
        "permission": "users.update",
        "phase": "F008",
    },
    {
        "endpoint": "/api/logistics/users/{id}/disable",
        "method": "PATCH",
        "permission": "users.disable",
        "phase": "F008",
    },
    {
        "endpoint": "/api/logistics/users/{id}/roles",
        "method": "PUT",
        "permission": "users.roles.assign",
        "phase": "F008",
    },
    # Document Catalog (F011)
    {
        "endpoint": "/api/logistics/document-families",
        "method": "GET",
        "permission": "document_catalog.read",
        "phase": "F011",
    },
    {
        "endpoint": "/api/logistics/document-families",
        "method": "POST",
        "permission": "document_catalog.manage",
        "phase": "F011",
    },
    {
        "endpoint": "/api/logistics/document-retention-policies",
        "method": "GET",
        "permission": "document_catalog.read",
        "phase": "F011",
    },
    {
        "endpoint": "/api/logistics/document-retention-policies",
        "method": "POST",
        "permission": "document_catalog.manage",
        "phase": "F011",
    },
    {
        "endpoint": "/api/logistics/document-types",
        "method": "GET",
        "permission": "document_catalog.read",
        "phase": "F011",
    },
    {
        "endpoint": "/api/logistics/document-types",
        "method": "POST",
        "permission": "document_catalog.manage",
        "phase": "F011",
    },
    {
        "endpoint": "/api/logistics/document-types/{id}",
        "method": "GET",
        "permission": "document_catalog.read",
        "phase": "F011",
    },
    {
        "endpoint": "/api/logistics/document-types/{id}",
        "method": "PATCH",
        "permission": "document_catalog.manage",
        "phase": "F011",
    },
    {
        "endpoint": "/api/logistics/document-types/{id}/versions",
        "method": "GET",
        "permission": "document_catalog.read",
        "phase": "F011",
    },
    {
        "endpoint": "/api/logistics/document-types/{id}/versions",
        "method": "POST",
        "permission": "document_catalog.manage",
        "phase": "F011",
    },
    {
        "endpoint": "/api/logistics/document-types/{id}/versions/{version}",
        "method": "GET",
        "permission": "document_catalog.read",
        "phase": "F011",
    },
    {
        "endpoint": "/api/logistics/document-numbering/standard",
        "method": "GET",
        "permission": "document_catalog.read",
        "phase": "F012",
    },
    {
        "endpoint": "/api/logistics/document-numbering/preview",
        "method": "POST",
        "permission": "document_catalog.read",
        "phase": "F012",
    },
    {
        "endpoint": "/api/logistics/document-series",
        "method": "GET",
        "permission": "document_series.read",
        "phase": "F013",
    },
    {
        "endpoint": "/api/logistics/document-series",
        "method": "POST",
        "permission": "document_series.create",
        "phase": "F013",
    },
    {
        "endpoint": "/api/logistics/document-series/{id}",
        "method": "GET",
        "permission": "document_series.read",
        "phase": "F013",
    },
    {
        "endpoint": "/api/logistics/document-series/{id}/reservations",
        "method": "POST",
        "permission": "document_series.reserve",
        "phase": "F013",
    },
    {
        "endpoint": "/api/logistics/document-series/reservations/{id}",
        "method": "GET",
        "permission": "document_series.read",
        "phase": "F013",
    },
    {
        "endpoint": "/api/logistics/document-series/{id}/numbers",
        "method": "GET",
        "permission": "document_series.read",
        "phase": "F013",
    },
    {
        "endpoint": "/api/logistics/document-series/numbers/{id}/void",
        "method": "POST",
        "permission": "document_series.void",
        "phase": "F013",
    },
    {
        "endpoint": "/api/logistics/document-series/reservations/{id}/booklet",
        "method": "GET",
        "permission": "document_series.download",
        "phase": "F013",
    },
]
