from typing import Any, Dict, List

CANONICAL_DOCUMENT_FAMILIES: List[Dict[str, Any]] = [
    {
        "code": "PURCHASING",
        "name": "Compras y Aprovisionamiento",
        "description": "Requerimientos, cotizaciones, órdenes de compra y aprobaciones",
    },
    {
        "code": "RECEIVING",
        "name": "Recepción e Ingresos",
        "description": "Control de citas, puertas, actas de recepción técnica y guías de ingreso",
    },
    {
        "code": "INVENTORY",
        "name": "Gestión de Inventario",
        "description": (
            "Etiquetas de ubicación, movimientos, ajustes, conteos físicos y transferencias"
        ),
    },
    {
        "code": "OUTBOUND",
        "name": "Salidas y Despacho",
        "description": "Solicitudes de salida, órdenes de despacho, picking, packing y manifiestos",
    },
    {
        "code": "TRANSPORT",
        "name": "Transporte y Flota",
        "description": "Planillas de viaje, hojas de ruta e inspección técnica vehicular",
    },
    {
        "code": "DELIVERY",
        "name": "Entrega y Liquidación",
        "description": "Constancias de entrega (POD), paradas, rechazos e incidencias en ruta",
    },
    {
        "code": "QUALITY",
        "name": "Control de Calidad",
        "description": "Reportes de no conformidad, inspecciones técnicas y cuarentenas",
    },
    {
        "code": "RETURN",
        "name": "Logística Inversa",
        "description": "Devoluciones a proveedor, devoluciones de clientes y mermas",
    },
    {
        "code": "SYSTEM",
        "name": "Documentos del Sistema",
        "description": "Reportes de auditoría, exportaciones administrativas y actas internas",
    },
]

CANONICAL_RETENTION_POLICIES: List[Dict[str, Any]] = [
    {
        "code": "OPERATIONAL_STANDARD",
        "name": "Operativa Estándar (1 Año)",
        "description": "Retención activa de 365 días para trazabilidad operativa cotidiana",
        "retention_days": 365,
        "retain_forever": False,
        "legal_hold_supported": True,
    },
    {
        "code": "AUDIT_RELEVANT",
        "name": "Relevancia de Auditoría (5 Años)",
        "description": (
            "Retención de 1825 días para control contable, tributario y de auditoría interna"
        ),
        "retention_days": 1825,
        "retain_forever": False,
        "legal_hold_supported": True,
    },
    {
        "code": "LEGAL_LONG_TERM",
        "name": "Custodia Legal (10 Años)",
        "description": "Retención de 3650 días según exigencias normativas y comerciales",
        "retention_days": 3650,
        "retain_forever": False,
        "legal_hold_supported": True,
    },
    {
        "code": "PERMANENT",
        "name": "Permanente / Histórica",
        "description": "Custodia indefinida sin purga automática",
        "retention_days": None,
        "retain_forever": True,
        "legal_hold_supported": True,
    },
    {
        "code": "UNDEFINED_PENDING_POLICY",
        "name": "Pendiente de Definición",
        "description": (
            "Política transitoria mientras se determinan los requisitos legales aplicables"
        ),
        "retention_days": None,
        "retain_forever": False,
        "legal_hold_supported": False,
    },
]

CANONICAL_DOCUMENT_TYPES: List[Dict[str, Any]] = [
    # --- PURCHASING ---
    {
        "code": "REQ",
        "name": "Requerimiento de Compra",
        "description": (
            "Solicitud interna de bienes o servicios para operaciones de almacén o transporte"
        ),
        "family_code": "PURCHASING",
        "document_scope": "INTERNAL",
        "phase_owner": "F015",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "requisition_v1",
        "schema_definition": [
            {"key": "requester_id", "label": "Solicitante", "type": "uuid", "required": True},
            {"key": "cost_center", "label": "Centro de Costo", "type": "text", "required": True},
            {"key": "required_date", "label": "Fecha Requerida", "type": "date", "required": True},
            {
                "key": "justification",
                "label": "Justificación",
                "type": "long_text",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_organization": True,
            "requires_branch": True,
            "requires_approval": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["DRAFT", "PENDING", "APPROVED", "REJECTED", "COMPLETED", "VOID"],
    },
    {
        "code": "RFQ",
        "name": "Solicitud de Cotización",
        "description": "Documento enviado a proveedores para cotizar precios y plazos de entrega",
        "family_code": "PURCHASING",
        "document_scope": "INTERNAL",
        "phase_owner": "F015",
        "retention_code": "OPERATIONAL_STANDARD",
        "template_key": "rfq_v1",
        "schema_definition": [
            {
                "key": "requisition_id",
                "label": "Requerimiento Asociado",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "supplier_ids",
                "label": "Proveedores Invitados",
                "type": "reference",
                "required": True,
            },
            {
                "key": "due_date",
                "label": "Fecha Límite de Recepción",
                "type": "date",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_organization": True,
            "requires_branch": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["DRAFT", "ISSUED", "CLOSED", "VOID"],
    },
    {
        "code": "CMP",
        "name": "Cuadro Comparativo de Ofertas",
        "description": "Evaluación técnica y económica de cotizaciones recibidas de proveedores",
        "family_code": "PURCHASING",
        "document_scope": "INTERNAL",
        "phase_owner": "F015",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "comparative_table_v1",
        "schema_definition": [
            {"key": "rfq_id", "label": "Cotización Asociada", "type": "uuid", "required": True},
            {
                "key": "winner_supplier_id",
                "label": "Proveedor Seleccionado",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "award_justification",
                "label": "Sustento de Selección",
                "type": "long_text",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_organization": True,
            "requires_approval": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["DRAFT", "PENDING", "APPROVED", "VOID"],
    },
    {
        "code": "PO",
        "name": "Orden de Compra",
        "description": "Compromiso contractual vinculante de compra emitido hacia el proveedor",
        "family_code": "PURCHASING",
        "document_scope": "INTERNAL",
        "phase_owner": "F015",
        "retention_code": "LEGAL_LONG_TERM",
        "template_key": "purchase_order_v1",
        "schema_definition": [
            {"key": "supplier_id", "label": "Proveedor", "type": "uuid", "required": True},
            {
                "key": "currency",
                "label": "Moneda",
                "type": "enum",
                "required": True,
                "options": ["PEN", "USD"],
            },
            {"key": "total_amount", "label": "Monto Total", "type": "decimal", "required": True},
            {
                "key": "payment_terms",
                "label": "Condición de Pago",
                "type": "text",
                "required": True,
            },
            {
                "key": "delivery_warehouse_id",
                "label": "Almacén de Entrega",
                "type": "uuid",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_organization": True,
            "requires_branch": True,
            "requires_warehouse": True,
            "requires_approval": True,
            "requires_step_up": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["DRAFT", "PENDING", "APPROVED", "ISSUED", "COMPLETED", "VOID"],
    },
    {
        "code": "POA",
        "name": "Aprobación de Compra",
        "description": "Autorización formal de gerencia o finanzas para emisión de Orden de Compra",
        "family_code": "PURCHASING",
        "document_scope": "INTERNAL",
        "phase_owner": "F015",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "purchase_approval_v1",
        "schema_definition": [
            {"key": "po_id", "label": "Orden de Compra", "type": "uuid", "required": True},
            {"key": "approver_id", "label": "Aprobador", "type": "uuid", "required": True},
            {
                "key": "approval_notes",
                "label": "Observaciones de Aprobación",
                "type": "text",
                "required": False,
            },
        ],
        "emission_rules": {
            "requires_organization": True,
            "requires_step_up": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["PENDING", "APPROVED", "REJECTED"],
    },
    {
        "code": "PSC",
        "name": "Confirmación de Envío de Proveedor",
        "description": "Aviso de despacho / ASN emitido externamente por el proveedor",
        "family_code": "PURCHASING",
        "document_scope": "EXTERNAL",
        "phase_owner": "F015",
        "retention_code": "OPERATIONAL_STANDARD",
        "template_key": None,
        "schema_definition": [
            {
                "key": "external_tracking_number",
                "label": "Nro Guía / Seguimiento Proveedor",
                "type": "text",
                "required": True,
            },
            {
                "key": "estimated_arrival_date",
                "label": "Fecha Estimada de Llegada",
                "type": "date",
                "required": True,
            },
            {"key": "po_id", "label": "Orden de Compra", "type": "uuid", "required": True},
        ],
        "emission_rules": {
            "preserve_external_number": True,
            "future_numbering_policy": "EXTERNAL_PRESERVED",
        },
        "status_definition": ["REGISTERED", "PROCESSED", "VOID"],
    },
    # --- RECEIVING ---
    {
        "code": "ARR",
        "name": "Cita de Llegada / Arribo",
        "description": "Programación de turno para descarga vehicular en muelle de recepción",
        "family_code": "RECEIVING",
        "document_scope": "INTERNAL",
        "phase_owner": "F016",
        "retention_code": "OPERATIONAL_STANDARD",
        "template_key": "arrival_appointment_v1",
        "schema_definition": [
            {"key": "warehouse_id", "label": "Almacén", "type": "uuid", "required": True},
            {
                "key": "supplier_id",
                "label": "Proveedor / Transportista",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "slot_start_time",
                "label": "Hora Inicio Turno",
                "type": "datetime",
                "required": True,
            },
            {
                "key": "vehicle_plate",
                "label": "Placa del Vehículo",
                "type": "text",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["SCHEDULED", "CHECKED_IN", "UNLOADED", "CANCELLED"],
    },
    {
        "code": "CPV",
        "name": "Control de Puerta Vehicular",
        "description": "Registro de ingreso y salida física de vehículos de carga en garita",
        "family_code": "RECEIVING",
        "document_scope": "INTERNAL",
        "phase_owner": "F016",
        "retention_code": "OPERATIONAL_STANDARD",
        "template_key": "gate_control_v1",
        "schema_definition": [
            {"key": "vehicle_plate", "label": "Placa Vehicular", "type": "text", "required": True},
            {"key": "driver_name", "label": "Conductor", "type": "text", "required": True},
            {"key": "driver_dni", "label": "DNI Conductor", "type": "text", "required": True},
            {"key": "entry_time", "label": "Hora Ingreso", "type": "datetime", "required": True},
            {"key": "exit_time", "label": "Hora Salida", "type": "datetime", "required": False},
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["INSIDE", "EXITED", "CANCELLED"],
    },
    {
        "code": "REC",
        "name": "Acta de Recepción Técnica",
        "description": "Constancia de inspección física y técnica de bultos recibidos en muelle",
        "family_code": "RECEIVING",
        "document_scope": "INTERNAL",
        "phase_owner": "F016",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "receiving_report_v1",
        "schema_definition": [
            {"key": "po_id", "label": "Orden de Compra", "type": "uuid", "required": True},
            {"key": "warehouse_id", "label": "Almacén", "type": "uuid", "required": True},
            {
                "key": "inspected_packages_count",
                "label": "Bultos Inspeccionados",
                "type": "integer",
                "required": True,
            },
            {
                "key": "technical_verdict",
                "label": "Dictamen Técnico",
                "type": "enum",
                "required": True,
                "options": ["CONFORM", "OBSERVED", "REJECTED"],
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "requires_step_up": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["DRAFT", "COMPLETED", "VOID"],
    },
    {
        "code": "GRN",
        "name": "Guía de Recepción en Almacén",
        "description": "Ingreso formal de existencias a los sistemas de inventario",
        "family_code": "RECEIVING",
        "document_scope": "INTERNAL",
        "phase_owner": "F016",
        "retention_code": "LEGAL_LONG_TERM",
        "template_key": "goods_receipt_v1",
        "schema_definition": [
            {"key": "po_id", "label": "Orden de Compra", "type": "uuid", "required": True},
            {"key": "supplier_id", "label": "Proveedor", "type": "uuid", "required": True},
            {"key": "warehouse_id", "label": "Almacén Destino", "type": "uuid", "required": True},
            {
                "key": "external_guide_number",
                "label": "Nro Guía Remitente",
                "type": "text",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "requires_step_up": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["DRAFT", "ISSUED", "CANCELLED"],
    },
    {
        "code": "RDIFF",
        "name": "Acta de Diferencias de Recepción",
        "description": (
            "Registro de faltantes, sobrantes o averías detectadas durante el conteo ciego"
        ),
        "family_code": "RECEIVING",
        "document_scope": "INTERNAL",
        "phase_owner": "F016",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "receiving_diff_v1",
        "schema_definition": [
            {"key": "grn_id", "label": "Guía de Recepción", "type": "uuid", "required": True},
            {
                "key": "discrepancy_type",
                "label": "Tipo de Discrepancia",
                "type": "enum",
                "required": True,
                "options": ["SHORTAGE", "EXCESS", "DAMAGED"],
            },
            {
                "key": "discrepancy_details",
                "label": "Detalle de Diferencias",
                "type": "long_text",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["OPEN", "RESOLVED", "VOID"],
    },
    {
        "code": "NC",
        "name": "Reporte de No Conformidad",
        "description": "Acta formal de rechazo por calidad, roturas o especificación técnica",
        "family_code": "RECEIVING",
        "document_scope": "INTERNAL",
        "phase_owner": "F016",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "non_conformity_v1",
        "schema_definition": [
            {"key": "supplier_id", "label": "Proveedor", "type": "uuid", "required": True},
            {"key": "reason_code", "label": "Motivo de Rechazo", "type": "text", "required": True},
            {
                "key": "action_required",
                "label": "Acción Requerida",
                "type": "enum",
                "required": True,
                "options": ["RETURN_TO_SUPPLIER", "PRICE_DISCOUNT", "SCRAP"],
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "requires_approval": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["ISSUED", "ACCEPTED_BY_SUPPLIER", "CLOSED"],
    },
    {
        "code": "GTR_EXT",
        "name": "Guía de Remisión Remitente Proveedor",
        "description": "Documento oficial del proveedor que acompaña físicamente a la mercadería",
        "family_code": "RECEIVING",
        "document_scope": "EXTERNAL",
        "phase_owner": "F016",
        "retention_code": "LEGAL_LONG_TERM",
        "template_key": None,
        "schema_definition": [
            {"key": "guide_series", "label": "Serie Guía", "type": "text", "required": True},
            {
                "key": "guide_number",
                "label": "Número Correlativo Guía",
                "type": "text",
                "required": True,
            },
            {"key": "supplier_ruc", "label": "RUC Proveedor", "type": "text", "required": True},
            {"key": "issue_date", "label": "Fecha de Emisión", "type": "date", "required": True},
        ],
        "emission_rules": {
            "preserve_external_number": True,
            "future_numbering_policy": "EXTERNAL_PRESERVED",
        },
        "status_definition": ["REGISTERED", "LINKED_TO_GRN", "ARCHIVED"],
    },
    # --- INVENTORY ---
    {
        "code": "LBL",
        "name": "Etiqueta de Ubicación / Pallet",
        "description": "Identificador físico de posición de estante, pallet o lote en almacén",
        "family_code": "INVENTORY",
        "document_scope": "INTERNAL",
        "phase_owner": "F017",
        "retention_code": "OPERATIONAL_STANDARD",
        "template_key": "location_label_v1",
        "schema_definition": [
            {
                "key": "location_code",
                "label": "Código de Ubicación",
                "type": "text",
                "required": True,
            },
            {"key": "warehouse_id", "label": "Almacén", "type": "uuid", "required": True},
            {
                "key": "barcode_payload",
                "label": "Contenido Código de Barras",
                "type": "text",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["ACTIVE", "OBSOLETE"],
    },
    {
        "code": "MOV",
        "name": "Movimiento Interno de Inventario",
        "description": "Reubicación física de stock entre posiciones de un mismo almacén",
        "family_code": "INVENTORY",
        "document_scope": "INTERNAL",
        "phase_owner": "F017",
        "retention_code": "OPERATIONAL_STANDARD",
        "template_key": "inventory_movement_v1",
        "schema_definition": [
            {"key": "warehouse_id", "label": "Almacén", "type": "uuid", "required": True},
            {
                "key": "origin_location",
                "label": "Ubicación Origen",
                "type": "text",
                "required": True,
            },
            {
                "key": "target_location",
                "label": "Ubicación Destino",
                "type": "text",
                "required": True,
            },
            {"key": "quantity", "label": "Cantidad Movida", "type": "decimal", "required": True},
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["EXECUTED", "CANCELLED"],
    },
    {
        "code": "INV_ADJ",
        "name": "Ajuste de Inventario",
        "description": (
            "Modificación manual controlada del stock por merma, desmedro o regularización"
        ),
        "family_code": "INVENTORY",
        "document_scope": "INTERNAL",
        "phase_owner": "F017",
        "retention_code": "LEGAL_LONG_TERM",
        "template_key": "inventory_adjustment_v1",
        "schema_definition": [
            {"key": "warehouse_id", "label": "Almacén", "type": "uuid", "required": True},
            {
                "key": "adjustment_type",
                "label": "Tipo de Ajuste",
                "type": "enum",
                "required": True,
                "options": ["INCREASE", "DECREASE"],
            },
            {"key": "reason_code", "label": "Motivo del Ajuste", "type": "text", "required": True},
            {
                "key": "total_cost_impact",
                "label": "Impacto Valorizado",
                "type": "decimal",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "requires_approval": True,
            "requires_step_up": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["DRAFT", "PENDING_APPROVAL", "APPROVED", "REJECTED"],
    },
    {
        "code": "CNT",
        "name": "Conteo Físico / Inventario Cíclico",
        "description": "Planilla de toma de inventario físico por cuadrilla en almacén",
        "family_code": "INVENTORY",
        "document_scope": "INTERNAL",
        "phase_owner": "F017",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "stock_count_v1",
        "schema_definition": [
            {"key": "warehouse_id", "label": "Almacén", "type": "uuid", "required": True},
            {
                "key": "count_method",
                "label": "Método de Conteo",
                "type": "enum",
                "required": True,
                "options": ["CYCLIC", "WALL_TO_WALL"],
            },
            {
                "key": "assigned_auditor_id",
                "label": "Auditor Responsable",
                "type": "uuid",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["IN_PROGRESS", "FINALIZED", "CANCELLED"],
    },
    {
        "code": "CDIFF",
        "name": "Diferencia de Conteo Físico",
        "description": "Balance comparativo entre stock teórico del sistema y conteo físico real",
        "family_code": "INVENTORY",
        "document_scope": "INTERNAL",
        "phase_owner": "F017",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "count_difference_v1",
        "schema_definition": [
            {"key": "count_id", "label": "Conteo Físico Origen", "type": "uuid", "required": True},
            {
                "key": "total_discrepancy_items",
                "label": "Ítems con Diferencia",
                "type": "integer",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["DRAFT", "RECONCILED", "APPROVED"],
    },
    {
        "code": "TRF",
        "name": "Solicitud de Transferencia entre Almacenes",
        "description": "Requerimiento de traspaso de existencias entre dos sedes de la empresa",
        "family_code": "INVENTORY",
        "document_scope": "INTERNAL",
        "phase_owner": "F017",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "transfer_request_v1",
        "schema_definition": [
            {
                "key": "origin_warehouse_id",
                "label": "Almacén Origen",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "destination_warehouse_id",
                "label": "Almacén Destino",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "dispatch_deadline",
                "label": "Fecha Límite de Envío",
                "type": "date",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_organization": True,
            "requires_branch": True,
            "requires_warehouse": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["DRAFT", "REQUESTED", "IN_TRANSIT", "COMPLETED", "CANCELLED"],
    },
    {
        "code": "TRF_REC",
        "name": "Recepción de Transferencia",
        "description": "Acta de conformidad de llegada de mercadería transferida",
        "family_code": "INVENTORY",
        "document_scope": "INTERNAL",
        "phase_owner": "F017",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "transfer_receipt_v1",
        "schema_definition": [
            {
                "key": "transfer_id",
                "label": "Transferencia Asociada",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "receiving_warehouse_id",
                "label": "Almacén Receptor",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "received_packages",
                "label": "Bultos Recibidos",
                "type": "integer",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["RECEIVED", "DISCREPANCY_FOUND", "CLOSED"],
    },
    # --- OUTBOUND ---
    {
        "code": "OUT_REQ",
        "name": "Solicitud de Salida de Almacén",
        "description": "Pedido interno o comercial de despacho de mercadería",
        "family_code": "OUTBOUND",
        "document_scope": "INTERNAL",
        "phase_owner": "F018",
        "retention_code": "OPERATIONAL_STANDARD",
        "template_key": "outbound_request_v1",
        "schema_definition": [
            {
                "key": "client_id",
                "label": "Cliente / Destinatario",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "origin_warehouse_id",
                "label": "Almacén de Salida",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "expected_dispatch_date",
                "label": "Fecha Prevista de Despacho",
                "type": "date",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["DRAFT", "PENDING_PICKING", "IN_PREPARATION", "READY", "CANCELLED"],
    },
    {
        "code": "ODS",
        "name": "Orden de Salida / Despacho",
        "description": "Instrucción formal de preparación y egreso físico de existencias",
        "family_code": "OUTBOUND",
        "document_scope": "INTERNAL",
        "phase_owner": "F018",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "outbound_order_v1",
        "schema_definition": [
            {
                "key": "outbound_request_id",
                "label": "Solicitud de Salida",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "priority",
                "label": "Prioridad",
                "type": "enum",
                "required": True,
                "options": ["NORMAL", "HIGH", "URGENT"],
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["CREATED", "IN_PROCESS", "DISPATCHED", "VOID"],
    },
    {
        "code": "PICK",
        "name": "Hoja / Lista de Picking",
        "description": "Ruta óptima de recolección de artículos por pasillo y nivel en almacén",
        "family_code": "OUTBOUND",
        "document_scope": "INTERNAL",
        "phase_owner": "F018",
        "retention_code": "OPERATIONAL_STANDARD",
        "template_key": "picking_list_v1",
        "schema_definition": [
            {
                "key": "outbound_order_id",
                "label": "Orden de Salida",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "picker_user_id",
                "label": "Operador Asignado",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "start_time",
                "label": "Hora Inicio Picking",
                "type": "datetime",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["PENDING", "PICKING", "COMPLETED", "SHORT_PICKED"],
    },
    {
        "code": "PACK",
        "name": "Lista de Empaque / Packing List",
        "description": "Detalle de embalaje, peso neto/bruto y distribución de cajas y bultos",
        "family_code": "OUTBOUND",
        "document_scope": "INTERNAL",
        "phase_owner": "F018",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "packing_list_v1",
        "schema_definition": [
            {
                "key": "outbound_order_id",
                "label": "Orden de Salida",
                "type": "uuid",
                "required": True,
            },
            {"key": "total_boxes", "label": "Total Cajas", "type": "integer", "required": True},
            {
                "key": "gross_weight_kg",
                "label": "Peso Bruto (kg)",
                "type": "decimal",
                "required": True,
            },
            {
                "key": "total_volume_m3",
                "label": "Volumen (m3)",
                "type": "decimal",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["DRAFT", "SEALED", "VOID"],
    },
    {
        "code": "MNF",
        "name": "Manifiesto de Carga",
        "description": (
            "Relación consolidada de todos los bultos y pedidos asignados a "
            "una unidad de transporte"
        ),
        "family_code": "OUTBOUND",
        "document_scope": "INTERNAL",
        "phase_owner": "F018",
        "retention_code": "LEGAL_LONG_TERM",
        "template_key": "manifest_v1",
        "schema_definition": [
            {
                "key": "trip_sheet_id",
                "label": "Planilla de Viaje",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "carrier_name",
                "label": "Empresa de Transporte",
                "type": "text",
                "required": True,
            },
            {
                "key": "total_orders_count",
                "label": "Cantidad de Pedidos",
                "type": "integer",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "requires_step_up": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["GENERATED", "LOADED", "IN_TRANSIT", "CLOSED"],
    },
    {
        "code": "DSP",
        "name": "Guía de Salida / Despacho",
        "description": (
            "Documento de constancia de egreso de almacén para control tributario y de custodia"
        ),
        "family_code": "OUTBOUND",
        "document_scope": "INTERNAL",
        "phase_owner": "F018",
        "retention_code": "LEGAL_LONG_TERM",
        "template_key": "dispatch_report_v1",
        "schema_definition": [
            {
                "key": "outbound_order_id",
                "label": "Orden de Salida",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "vehicle_plate",
                "label": "Placa del Vehículo",
                "type": "text",
                "required": True,
            },
            {"key": "driver_dni", "label": "DNI Conductor", "type": "text", "required": True},
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "requires_step_up": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["EMITTED", "CANCELLED"],
    },
    {
        "code": "SEAL",
        "name": "Acta de Control de Precintos",
        "description": (
            "Registro de números de serie de precintos de seguridad colocados en contenedor/furgón"
        ),
        "family_code": "OUTBOUND",
        "document_scope": "INTERNAL",
        "phase_owner": "F018",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "seal_control_v1",
        "schema_definition": [
            {
                "key": "manifest_id",
                "label": "Manifiesto de Carga",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "seal_numbers",
                "label": "Códigos de Precintos",
                "type": "text",
                "required": True,
            },
            {
                "key": "supervisor_id",
                "label": "Supervisor de Carga",
                "type": "uuid",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_warehouse": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["PLACED", "VERIFIED", "BROKEN_ON_ARRIVAL"],
    },
    # --- TRANSPORT & DELIVERY ---
    {
        "code": "TRIP",
        "name": "Planilla de Viaje",
        "description": "Planificación y liquidación operativa de un viaje de transporte",
        "family_code": "TRANSPORT",
        "document_scope": "INTERNAL",
        "phase_owner": "F019",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "trip_sheet_v1",
        "schema_definition": [
            {"key": "driver_id", "label": "Conductor Titular", "type": "uuid", "required": True},
            {
                "key": "vehicle_id",
                "label": "Unidad de Transporte",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "start_mileage",
                "label": "Kilometraje Inicial",
                "type": "decimal",
                "required": True,
            },
            {
                "key": "end_mileage",
                "label": "Kilometraje Final",
                "type": "decimal",
                "required": False,
            },
        ],
        "emission_rules": {
            "requires_organization": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["PLANNED", "ACTIVE", "COMPLETED", "CANCELLED"],
    },
    {
        "code": "ROUTE",
        "name": "Hoja de Ruta de Distribución",
        "description": "Secuencia cronológica de paradas de entrega y recojo asignadas",
        "family_code": "TRANSPORT",
        "document_scope": "INTERNAL",
        "phase_owner": "F019",
        "retention_code": "OPERATIONAL_STANDARD",
        "template_key": "route_sheet_v1",
        "schema_definition": [
            {
                "key": "trip_sheet_id",
                "label": "Planilla de Viaje",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "total_stops",
                "label": "Cantidad de Paradas",
                "type": "integer",
                "required": True,
            },
        ],
        "emission_rules": {
            "requires_organization": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["SCHEDULED", "IN_EXECUTION", "COMPLETED"],
    },
    {
        "code": "VEH",
        "name": "Inspección y Control Vehicular",
        "description": (
            "Checklist pre-operativo de seguridad de neumáticos, luces, frenos y documentación"
        ),
        "family_code": "TRANSPORT",
        "document_scope": "INTERNAL",
        "phase_owner": "F019",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "vehicle_inspection_v1",
        "schema_definition": [
            {"key": "vehicle_plate", "label": "Placa", "type": "text", "required": True},
            {"key": "inspector_id", "label": "Inspector", "type": "uuid", "required": True},
            {
                "key": "status_verdict",
                "label": "Veredicto Mecánico",
                "type": "enum",
                "required": True,
                "options": ["APT", "REJECTED_NEEDS_MAINTENANCE"],
            },
        ],
        "emission_rules": {
            "requires_organization": True,
            "future_numbering_policy": "SYSTEM_INTERNAL",
        },
        "status_definition": ["APPROVED", "REJECTED"],
    },
    {
        "code": "STOP",
        "name": "Registro de Parada / Visita",
        "description": "Bitácora GPS y temporal de arribo a punto de entrega de cliente",
        "family_code": "DELIVERY",
        "document_scope": "INTERNAL",
        "phase_owner": "F019",
        "retention_code": "OPERATIONAL_STANDARD",
        "template_key": "stop_record_v1",
        "schema_definition": [
            {"key": "route_sheet_id", "label": "Hoja de Ruta", "type": "uuid", "required": True},
            {
                "key": "client_name",
                "label": "Nombre del Punto de Entrega",
                "type": "text",
                "required": True,
            },
            {"key": "arrived_at", "label": "Hora de Arribo", "type": "datetime", "required": True},
            {
                "key": "departed_at",
                "label": "Hora de Salida",
                "type": "datetime",
                "required": False,
            },
        ],
        "emission_rules": {"future_numbering_policy": "SYSTEM_INTERNAL"},
        "status_definition": ["PENDING", "ARRIVED", "FINISHED"],
    },
    {
        "code": "INC",
        "name": "Reporte de Incidente en Ruta",
        "description": "Registro de atascos viales, pinchazos, siniestros o demoras operativas",
        "family_code": "DELIVERY",
        "document_scope": "INTERNAL",
        "phase_owner": "F019",
        "retention_code": "AUDIT_RELEVANT",
        "template_key": "incident_report_v1",
        "schema_definition": [
            {
                "key": "trip_sheet_id",
                "label": "Planilla de Viaje",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "incident_type",
                "label": "Tipo de Incidente",
                "type": "enum",
                "required": True,
                "options": ["ACCIDENT", "BREAKDOWN", "TRAFFIC_DELAY", "CUSTOMER_ABSENT"],
            },
            {
                "key": "description",
                "label": "Descripción de lo Ocurrido",
                "type": "long_text",
                "required": True,
            },
        ],
        "emission_rules": {"future_numbering_policy": "SYSTEM_INTERNAL"},
        "status_definition": ["REPORTED", "INVESTIGATING", "RESOLVED"],
    },
    {
        "code": "POD",
        "name": "Constancia de Entrega / Proof of Delivery",
        "description": "Acta de conformidad final firmada y sellada por el cliente receptor",
        "family_code": "DELIVERY",
        "document_scope": "INTERNAL",
        "phase_owner": "F019",
        "retention_code": "LEGAL_LONG_TERM",
        "template_key": "proof_of_delivery_v1",
        "schema_definition": [
            {
                "key": "outbound_order_id",
                "label": "Orden de Salida",
                "type": "uuid",
                "required": True,
            },
            {
                "key": "received_by_name",
                "label": "Persona que Recibe",
                "type": "text",
                "required": True,
            },
            {
                "key": "received_by_dni",
                "label": "DNI / Documento Receptor",
                "type": "text",
                "required": True,
            },
            {
                "key": "delivery_status",
                "label": "Resultado de la Entrega",
                "type": "enum",
                "required": True,
                "options": ["FULL_DELIVERY", "PARTIAL_DELIVERY", "REJECTED"],
            },
        ],
        "emission_rules": {"requires_step_up": True, "future_numbering_policy": "SYSTEM_INTERNAL"},
        "status_definition": ["CONFORM", "OBSERVED", "REJECTED"],
    },
    {
        "code": "REJ",
        "name": "Acta de Rechazo de Entrega",
        "description": "Constancia formal de no recepción de mercadería por parte del cliente",
        "family_code": "DELIVERY",
        "document_scope": "INTERNAL",
        "phase_owner": "F019",
        "retention_code": "LEGAL_LONG_TERM",
        "template_key": "delivery_rejection_v1",
        "schema_definition": [
            {"key": "pod_id", "label": "Constancia de Entrega", "type": "uuid", "required": True},
            {
                "key": "rejection_reason",
                "label": "Motivo del Rechazo",
                "type": "text",
                "required": True,
            },
        ],
        "emission_rules": {"requires_reason": True, "future_numbering_policy": "SYSTEM_INTERNAL"},
        "status_definition": ["REJECTED", "RETURNED_TO_WAREHOUSE"],
    },
    {
        "code": "PDEL",
        "name": "Acta de Entrega Parcial",
        "description": "Detalle de ítems aceptados y devueltos en punto de descarga",
        "family_code": "DELIVERY",
        "document_scope": "INTERNAL",
        "phase_owner": "F019",
        "retention_code": "LEGAL_LONG_TERM",
        "template_key": "partial_delivery_v1",
        "schema_definition": [
            {"key": "pod_id", "label": "Constancia de Entrega", "type": "uuid", "required": True},
            {
                "key": "accepted_items_count",
                "label": "Ítems Aceptados",
                "type": "integer",
                "required": True,
            },
            {
                "key": "returned_items_count",
                "label": "Ítems Retornados",
                "type": "integer",
                "required": True,
            },
        ],
        "emission_rules": {"requires_reason": True, "future_numbering_policy": "SYSTEM_INTERNAL"},
        "status_definition": ["PARTIAL_CONFORM", "SETTLED"],
    },
]
