import uuid

from fastapi import APIRouter, Depends, Request, Response
from sqlalchemy.orm import Session

from app.core.rbac import AuthenticatedPrincipal
from app.db.connection import get_db
from app.modules.auth.dependencies import (
    get_current_principal,
    validate_csrf,
)
from app.modules.auth.mfa_service import MfaService
from app.modules.auth.schemas import (
    MfaDisableRequest,
    MfaRecoveryRegenerateResponse,
    MfaStatusResponse,
    MfaTotpConfirmRequest,
    MfaTotpConfirmResponse,
    MfaTotpEnrollRequest,
    MfaTotpEnrollResponse,
    StepUpVerifyRequest,
    StepUpVerifyResponse,
)
from app.modules.auth.step_up import StepUpPolicyEngine

mfa_service = MfaService()
step_up_engine = StepUpPolicyEngine()

mfa_router = APIRouter(prefix="/api/auth", tags=["MFA & Step-Up Authentication"])


@mfa_router.get(
    "/mfa/status",
    response_model=MfaStatusResponse,
    summary="Get user MFA configuration status and remaining recovery codes count",
)
def get_mfa_status(
    principal: AuthenticatedPrincipal = Depends(get_current_principal),
    db: Session = Depends(get_db),
) -> MfaStatusResponse:
    enabled, methods, remaining = mfa_service.get_mfa_status(db, principal.user_id)
    return MfaStatusResponse(
        enabled=enabled,
        methods=methods,
        recovery_codes_remaining=remaining,
    )


@mfa_router.post(
    "/mfa/totp/enroll",
    response_model=MfaTotpEnrollResponse,
    summary="Initiate TOTP enrollment (requires password re-authentication)",
    dependencies=[Depends(validate_csrf)],
)
def enroll_totp(
    data: MfaTotpEnrollRequest,
    request: Request,
    principal: AuthenticatedPrincipal = Depends(get_current_principal),
    db: Session = Depends(get_db),
) -> MfaTotpEnrollResponse:
    correlation_id = getattr(request.state, "correlation_id", None)
    factor_id, manual_key, otpauth_url = mfa_service.enroll_totp(
        db=db,
        user_id=principal.user_id,
        current_password=data.current_password,
        correlation_id=correlation_id,
    )

    qr_endpoint = f"/api/auth/mfa/totp/enrollments/{factor_id}/qr"
    return MfaTotpEnrollResponse(
        enrollment_id=factor_id,
        manual_key=manual_key,
        qr_endpoint=qr_endpoint,
        otpauth_url=otpauth_url,
    )


@mfa_router.get(
    "/mfa/totp/enrollments/{enrollment_id}/qr",
    summary="Get PNG QR code generated by backend for TOTP enrollment",
    responses={200: {"content": {"image/png": {}}}},
)
def get_enrollment_qr(
    enrollment_id: uuid.UUID,
    principal: AuthenticatedPrincipal = Depends(get_current_principal),
    db: Session = Depends(get_db),
) -> Response:
    png_bytes = mfa_service.generate_qr_image_bytes(
        db=db,
        user_id=principal.user_id,
        enrollment_id=enrollment_id,
    )
    return Response(
        content=png_bytes,
        media_type="image/png",
        headers={"Cache-Control": "no-store, no-cache, must-revalidate, max-age=0"},
    )


@mfa_router.post(
    "/mfa/totp/confirm",
    response_model=MfaTotpConfirmResponse,
    summary="Confirm TOTP code, activate MFA factor and issue single-use recovery codes",
    dependencies=[Depends(validate_csrf)],
)
def confirm_totp(
    data: MfaTotpConfirmRequest,
    request: Request,
    principal: AuthenticatedPrincipal = Depends(get_current_principal),
    db: Session = Depends(get_db),
) -> MfaTotpConfirmResponse:
    correlation_id = getattr(request.state, "correlation_id", None)
    factor_id, recovery_codes = mfa_service.confirm_totp(
        db=db,
        user_id=principal.user_id,
        enrollment_id=data.enrollment_id,
        code=data.code,
        correlation_id=correlation_id,
    )
    return MfaTotpConfirmResponse(
        status="ACTIVE",
        factor_id=factor_id,
        recovery_codes=recovery_codes,
    )


@mfa_router.post(
    "/mfa/disable",
    summary="Disable MFA for user (requires current password)",
    dependencies=[Depends(validate_csrf)],
)
def disable_mfa(
    data: MfaDisableRequest,
    request: Request,
    principal: AuthenticatedPrincipal = Depends(get_current_principal),
    db: Session = Depends(get_db),
) -> dict:
    correlation_id = getattr(request.state, "correlation_id", None)
    mfa_service.disable_mfa(
        db=db,
        user_id=principal.user_id,
        current_password=data.current_password,
        correlation_id=correlation_id,
    )
    return {"status": "mfa_disabled"}


@mfa_router.post(
    "/mfa/recovery-codes/regenerate",
    response_model=MfaRecoveryRegenerateResponse,
    summary="Regenerate single-use recovery codes (invalidates previous codes)",
    dependencies=[Depends(validate_csrf)],
)
def regenerate_recovery_codes(
    request: Request,
    principal: AuthenticatedPrincipal = Depends(get_current_principal),
    db: Session = Depends(get_db),
) -> MfaRecoveryRegenerateResponse:
    correlation_id = getattr(request.state, "correlation_id", None)
    new_codes = mfa_service.regenerate_recovery_codes(
        db=db,
        user_id=principal.user_id,
        correlation_id=correlation_id,
    )
    return MfaRecoveryRegenerateResponse(recovery_codes=new_codes)


@mfa_router.post(
    "/step-up/verify",
    response_model=StepUpVerifyResponse,
    summary="Verify step-up challenge using TOTP code or recovery code",
    dependencies=[Depends(validate_csrf)],
)
def verify_step_up(
    data: StepUpVerifyRequest,
    request: Request,
    principal: AuthenticatedPrincipal = Depends(get_current_principal),
    db: Session = Depends(get_db),
) -> StepUpVerifyResponse:
    correlation_id = getattr(request.state, "correlation_id", None)
    grant = step_up_engine.verify_step_up(
        db=db,
        user_id=principal.user_id,
        session_id=principal.session_id,
        challenge_id=data.challenge_id,
        method=data.method,
        code=data.code,
        correlation_id=correlation_id,
    )
    return StepUpVerifyResponse(
        status="VERIFIED",
        grant_id=grant.id,
        policy_code=grant.policy_code,
        expires_at=grant.expires_at,
    )
